remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"
title: "&e Tech"
subtitle: Software engineering and DevOps Consulting
description: Software engineering and DevOps Consulting
url: "https://and-e.tech"
repository: "themitchell/and-e.tech"
timezone: Europe/London
logo: "/assets/images/and-e-tech-logo-300.svg"

plugins:
  - jekyll-include-cache

include:
  - "_pages"
  - "_katas"

author:
  name: "Andy Mitchell"
  avatar: "/assets/images/avatar.jpg"
  bio: "Software engineer and DevOps consultant"
  links:
    - label: "and-e.tech"
      icon: "fas fa-fw fa-link"
      url: "https://and-e.tech"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/themitchell"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andy-mitchell-46b699215/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: katas
    values:
      layout: single
      author_profile: false
      share: true
  - scope:
      path: ""
      type: workshops
    values:
      layout: single
      author_profile: false
      share: true

collections:
  katas:
    output: true
    permalink: /:collection/:path/
  workshops:
    output: true
    permalink: /:collection/:path/

analytics:
  provider: "google-gtag"
  google:
    measurement_id: "G-SPZK39FN6E"
    anonymize_ip: true

footer:
  links:
    - label: "and-e.tech"
      icon: "fas fa-fw fa-link"
      url: "https://and-e.tech"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/themitchell"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andy-mitchell-46b699215/"
